### ISSUE TITLE
[re3] Windows D3D9 64bit build won't start

### ISSUE THREAD

**Issue by madicines** [GTAmodding/re3#1162]
I start the game with "re3.exe" file. The game icon appears on a task panel but there's no the game window. I press Alt+Tab to try to bring the game window to front but an error appears:

![image](https://user-images.githubusercontent.com/74488165/123545155-556cf100-d75f-11eb-80c7-e7f7a8638744.png)

Windows D3D9 MSS 32bit and Windows OpenGL 64bit builds work fine. Release builds work too.
System: Windows 10, all VC++ Redists (2005-2015) are installed.

**Comment by madicines** [comment]
The error still exists after #1168. 

![image](https://user-images.githubusercontent.com/74488165/123560771-fdf57200-d7ac-11eb-8460-32d2f6b10330.png)

The game starts normally if make few mouse clicks instead of Alt+Tab. Obviously the issue related to intro videos playing.

**Comment by erorcun** [comment]
It turned out to be vanilla bug.

It should be fixed if you try the PR again.

**Comment by madicines** [comment]
@erorcun, thank you! I just  tried the last PR, but the issue is still here. There's no error anymore after Alt+Tab but the game icon disappears from a task panel after that (it seems like the game process crashes). As i said before after two mouse clicks the game starts normally. I've set NoMovies value to 1 in re3.ini so far.
