### ISSUE TITLE
[re3] Dodo can't fly

### ISSUE THREAD

**Issue by temptdit** [GTAmodding/re3#1312]
Here's a video:
https://www.youtube.com/watch?v=OGy22iZ__mE

**Comment by dquark** [comment]
It's normal, that's how it works in every version, regardless of platform

**Comment by erorcun** [comment]
The problem in here was sparks weren't visible when using free cam. Should be fixed with this: https://github.com/GTAmodding/re3/commit/e9a61ca38cd88a9c8b15b00a1ada73dd7d85c46f, but you should use closest distance mode.

**Comment by temptdit** [comment]
The sparks are indeed there, but it still doesn't fly, like it did in the Steam version
https://www.youtube.com/watch?v=exEtTmEVvrE

**Comment by erorcun** [comment]
It flies without problem on at least 2 people on the team, also I've compared flight control function and it looks correct, sorry.

**Comment by Nick007J** [comment]
I will check the flying function again a bit later just in case.
